In [2]:
import numpy as np

## Creating Numpy Arrays from Python Lists

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [5]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
a1 = np.array([1,2,3,4])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2,3], 
              [4,5,6]])

In [11]:
a2.shape

(2, 3)

In [12]:
a2.ndim

2

In [13]:
a2.dtype

dtype('int32')

In [14]:
a2.size

6

## Creating Numpy Arrays from Scratch

### `zeros`, `ones`, `full`, `arange`, `linspace`

In [15]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones([2,4], dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [19]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [20]:
# seed for reproducibility
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [21]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [22]:
np.random.randint(0, 10, (4, 5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [23]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

### Array indexing & Slicing 
## One-dimensional subarray

In [25]:
x1 = np.random.randint(20,size = 6)

In [26]:
x1

array([ 3,  0,  5,  0, 17, 18])

In [27]:
x1[0], x1[4], x1[-1]

(3, 17, 18)

## Multi-dimensional array

In [28]:
x2 = np.random.randint(10,size = (3,4))

In [29]:
x2

array([[4, 2, 0, 3],
       [2, 0, 7, 5],
       [9, 0, 2, 7]])

In [41]:
x2[0,-1], x2[-1,-1]

(3, 7)

In [33]:
x2[0][0] = 6

In [34]:
x2

array([[6, 2, 0, 3],
       [2, 0, 7, 5],
       [9, 0, 2, 7]])

## Slicing: x[start:stop:step]

In [35]:
x1

array([ 3,  0,  5,  0, 17, 18])

In [36]:
x1[0:3]

array([3, 0, 5])

In [37]:
x1[::2]

array([ 3,  5, 17])

In [38]:
x2

array([[6, 2, 0, 3],
       [2, 0, 7, 5],
       [9, 0, 2, 7]])

In [40]:
x2[:2,:3]

array([[6, 2, 0],
       [2, 0, 7]])

In [42]:
x2[:2][:3]

array([[6, 2, 0, 3],
       [2, 0, 7, 5]])

In [43]:
x2[:,:2]

array([[6, 2],
       [2, 0],
       [9, 0]])

### Reshaping of array & transpose

In [45]:
grid = np.arange(1,10)
grid.shape

(9,)

In [46]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
x = np.array([[1.,2.],[3.,4.]])

In [48]:
x

array([[1., 2.],
       [3., 4.]])

In [49]:
x.T

array([[1., 3.],
       [2., 4.]])

### Array concatenation and splitting

In [50]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [51]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [56]:
x = np.array([[1,2,3],[6,5,4]])
grid = np.array([[1,2,3],[4,5,6]])

In [57]:
np.vstack((x,grid))

array([[1, 2, 3],
       [6, 5, 4],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
np.hstack((x,grid))

array([[1, 2, 3, 1, 2, 3],
       [6, 5, 4, 4, 5, 6]])

## splitting of array

In [59]:
x = np.array([1,2,3,4,5])

In [61]:
x1, x2, x3 = np.split(x, [3,5])

In [62]:
x1 

array([1, 2, 3])

In [63]:
x2

array([4, 5])

In [64]:
x3

array([], dtype=int32)

### Broadcasting and Vectorized operations

In [66]:
a = np.arange(3)

In [67]:
a 

array([0, 1, 2])

In [69]:
a + 5 # broadcasting

array([5, 6, 7])